### ISSUE TITLE
Status bar from popup menu is overlapping

### ISSUE THREAD

**Issue by bytao7mao** [WalkInProgress/ProteinTracker-ChromeExtension#22]
The status bar from popup menu is overlapping.

**Comment by vasilevladilie** [comment]
I've seen a comment where @jmaldia said that he will take care of it. If he doesn't I'll do it later today.

**Comment by jmaldia** [comment]
I'll look into this.

**Comment by bytao7mao** [comment]
for easier debugging - > popup.html + progres.css == status bar

**Comment by jmaldia** [comment]
I sent a PR for this.

**Comment by bytao7mao** [comment]
closed! thanks!
