### ISSUE TITLE
Implementing easter theme for the first beta launch

### ISSUE THREAD

**Issue by bytao7mao** [WalkInProgress/ProteinTracker-ChromeExtension#25]

**Comment by vasilevladilie** [comment]
I'm thinking about egg shaped buttons, a rabbit for the progress bar and some easter food as the image. Maybe we can change the logo that's on the upper bar to a bunny or an egg. Let's collect free easter items pictures and send them on slack.

**Comment by jmaldia** [comment]
@bytao7mao Made another PR - added easter text

**Comment by bytao7mao** [comment]
Perfect ! issue closed !
