### ISSUE TITLE
Adding personal choices for user

### ISSUE THREAD

**Issue by bytao7mao** [WalkInProgress/ProteinTracker-ChromeExtension#3]
Adding some feature for the user to input his personal bio like: years, gender, weight, meals per day.
Using Bootstrap to display this would be a good choice.

**Comment by jmaldia** [comment]
I think I can build the form. Do you want this added to the options.html file or a separate file? I've never worked on an extension before. Does the data get stored somewhere? We can maybe split the work on this too if you want - front end and the handling of data.

**Comment by vasilevladilie** [comment]
The data is stored in the chrome storage. You can use methods and listeners to get the values or to store them. There is chrome.storage.sync.set, search on google for details, that is for set a field in the chrome store.
Let's collaborate on this issue. I'll do the ES6-Javascript part.

**Comment by jmaldia** [comment]
Sounds good. Let me know what the process is? Should I just start coding the form? Sorry newbie to this.

**Comment by vasilevladilie** [comment]
Join slack: wALk in Progress. Add yourself to the contributors... just read the 2 Readmes. And modify the options.html, add there the form. Push the change, I'll push mine in parallel.

**Comment by jmaldia** [comment]
Thanks. How can I get an invite to slack channel?

**Comment by vasilevladilie** [comment]
You just sign in to your slack account and then add the workspace with the name wALk in Progress that's it.

**Comment by bytao7mao** [comment]
@jmaldia tell me your e-mail to send you an invite to slack

**Comment by bytao7mao** [comment]
@jmaldia also for this to question "I think I can build the form. Do you want this added to the options.html file or a separate file?"

You can decide for yourself where do you want to implement the code :)

**Comment by jmaldia** [comment]
@bytao7mao Thanks. I just sent you an email with my email address.

**Comment by DennisKnie** [comment]
Has anyone started adding the input boxes in html for the user info? I can go ahead and add them to the options.html file and you will be able to do the js for the form. Just let me know and I will start once I get off work today.

**Comment by bytao7mao** [comment]
@DennisKnie you can go ahead for options.html.

**Comment by DennisKnie** [comment]
Alright. As soon as I get home I will open the latest version and start working on it. I may need to change a lot of things to really get it to look good and work.

**Comment by bytao7mao** [comment]
@DennisKnie take your time ! I will contribute tommorow night with some fixes too, thanks for your time Dennis !

**Comment by jmaldia** [comment]
Sorry I went MIA. Things got busy here. I'm glad @DennisKnie was able to jump in. If I see any other issue I can work on, I'll hop on it.

**Comment by bytao7mao** [comment]
closed!

**Comment by vasilevladilie** [comment]
@bytao7mao I forgot to tell you that even if I'm admin I can't close the issues for which I'm not the issuer. I have no button for close. :-D. Maybe more permissions are needed in order to do so.

**Comment by bytao7mao** [comment]
@vasilevladilie it seems that your role is not updated yet :| i'll try again to change your role
