### ISSUE TITLE
Publish the extension in Chrome Web Store

### ISSUE THREAD

**Issue by vasilevladilie** [WalkInProgress/ProteinTracker-ChromeExtension#31]
Publish the extension in Chrome Store
    See what problems are with this step.
    -> First problem seen is that we need a presentation page - a site for the extension - an idea is to use the about.html page of the app itself as the site of the extension. We may need another repository for the about page.

**Comment by bytao7mao** [comment]
we have to delay it a few days. see more on our slack channel.

**Comment by bytao7mao** [comment]
done
