### ISSUE TITLE
Design for options and popup

### ISSUE THREAD

**Issue by bytao7mao** [WalkInProgress/ProteinTracker-ChromeExtension#4]
We are in need of a nice designer who can create and implement into our chrome extension.

**Comment by iakhator** [comment]
Can we get details of the design needed?

**Comment by DennisKnie** [comment]
I have some free license stock photos but would need some details to find what works.

**Comment by iakhator** [comment]
If I can get someone to draw up the design, then I will implement it.

**Comment by bytao7mao** [comment]
I have no ideea about design but i can give you some link of examples

**Comment by bytao7mao** [comment]
a progress bar like this would be nice for keeping track of proteins, also more fitness oriented design would be cool.
https://imgur.com/a/xFBHW

**Comment by bytao7mao** [comment]
Also take a look here https://chrome.google.com/webstore/detail/notebook-web-clipper/cneaciknhhaahhdediboeafhdlbdoodg?hl=en-US

the design is nice from the popup window

**Comment by jmaldia** [comment]
Is there anyone working on this? If not, I can work on it.

**Comment by vasilevladilie** [comment]
Did you join slack @jmaldia ? Please pull the latest repo contents and check what was implemented,  @DennisKnie did some pushes yesterday on this issue. I'll work today on the js part.

**Comment by jmaldia** [comment]
Yea, I'm on slack now. I have the latest code. Was there anything else to be done (HTML wise) to the inputs? This is a different issue though, right? It's for design, no?

**Comment by bytao7mao** [comment]
@jmaldia you can share your ideas if you have for a improving our design

**Comment by jmaldia** [comment]
@bytao7mao I was thinking of working on the CSS based on the links you posted here. I like flat ui design. So, it would be something along those lines.

**Comment by jmaldia** [comment]
@bytao7mao - What do you think of this? http://screen.ac/2R1R2p182M1N

**Comment by bytao7mao** [comment]
@jmaldia hi there, yes i personally would love this implementation :) you can go ahead ! I'm eager to see it in our app 👍

**Comment by bytao7mao** [comment]
@jmaldia instead of the blue heart you can add some protein icon to represent our idea

**Comment by jmaldia** [comment]
@bytao7mao Sounds good. I was trying to find some icon that would represent protein. I'll see if I can find something else.

**Comment by bytao7mao** [comment]
@jmaldia or you can place our icon from img folder, the smaller icon is icon.png, till we find one better or till we make one in photoshop/illustrator

**Comment by jmaldia** [comment]
@bytao7mao, sorry I didn't see that before. I should've looked there. I changed the icon and color scheme. Let me know what you think. http://screen.ac/3t2c2I03242h

**Comment by bytao7mao** [comment]
@jmaldia i love it 💜

**Comment by jmaldia** [comment]
PR issued for the options.html redesign.

**Comment by bytao7mao** [comment]
the app looks very nice now, thanks to all who helped, and specially to @jmaldia and @DennisKnie

**Comment by bytao7mao** [comment]
closed!
